# Generated by Django 5.2.17 on 2026-09-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True, verbose_name='شناسه منبع')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان محصول')),
                ('original_slug', models.SlugField(allow_unicode=True, max_length=500, verbose_name='اسلاگ اصلی')),
                ('target_slug', models.SlugField(allow_unicode=True, blank=True, help_text='پیش\u200cفرض: اسلاگ اصلی. قابل ویرایش قبل از ارسال.', max_length=500, verbose_name='اسلاگ مقصد')),
                ('product_type', models.CharField(choices=[('simple', 'ساده'), ('variable', 'متغیر')], default='simple', max_length=20, verbose_name='نوع محصول')),
                ('target_keywords', models.TextField(blank=True, default='', help_text='کلمات کلیدی جدا شده با کاما', verbose_name='کلمات کلیدی هدف')),
                ('original_desc', models.TextField(blank=True, default='', verbose_name='توضیحات اصلی')),
                ('generated_desc', models.TextField(blank=True, default='', verbose_name='توضیحات تولید شده')),
                ('original_short_desc', models.TextField(blank=True, default='', verbose_name='توضیحات کوتاه اصلی')),
                ('generated_short_desc', models.TextField(blank=True, default='', verbose_name='توضیحات کوتاه تولید شده')),
                ('attributes', models.JSONField(blank=True, default=list, verbose_name='ویژگی\u200cها')),
                ('images_data', models.JSONField(blank=True, default=list, help_text='فرمت: [{"src": "url", "alt": "text"}]', verbose_name='تصاویر')),
                ('variations_data', models.JSONField(blank=True, default=list, help_text='داده\u200cهای تنوع محصول متغیر (قیمت، موجودی، …)', verbose_name='تنوع\u200cها')),
                ('status', models.CharField(choices=[('fetched', 'دریافت شده'), ('ai_processing', 'در حال پردازش AI'), ('ready_for_review', 'آماده بررسی'), ('approved', 'تأیید شده'), ('synced', 'همگام\u200cسازی شده')], db_index=True, default='fetched', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول همگام\u200cسازی',
                'verbose_name_plural': 'محصولات همگام\u200cسازی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قالب')),
                ('main_desc_prompt', models.TextField(help_text='دستورالعمل بازنویسی توضیحات اصلی محصول', verbose_name='پرامپت توضیحات اصلی')),
                ('short_desc_prompt', models.TextField(help_text='دستورالعمل بازنویسی توضیحات کوتاه محصول', verbose_name='پرامپت توضیحات کوتاه')),
                ('is_active', models.BooleanField(default=False, help_text='فقط یک قالب می\u200cتواند فعال باشد', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب پرامپت',
                'verbose_name_plural': 'قالب\u200cهای پرامپت',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
