# Generated by Django 5.2.17 on 2026-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_source_url', models.URLField(blank=True, default='', help_text='مثال: https://source-store.com', verbose_name='آدرس سایت منبع')),
                ('wc_source_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Consumer Key منبع')),
                ('wc_source_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Consumer Secret منبع')),
                ('wc_target_url', models.URLField(blank=True, default='', help_text='مثال: https://target-store.com', verbose_name='آدرس سایت مقصد')),
                ('wc_target_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Consumer Key مقصد')),
                ('wc_target_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Consumer Secret مقصد')),
                ('openrouter_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='کلید API اوپن\u200cروتر')),
                ('openrouter_model', models.CharField(blank=True, default='openai/gpt-4o', help_text='مثال: openai/gpt-4o, anthropic/claude-3.5-sonnet', max_length=100, verbose_name='مدل AI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات API',
                'verbose_name_plural': 'تنظیمات API',
            },
        ),
    ]
