# Generated by Django 5.2.17 on 2026-09-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0002_apisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openrouter_api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='کلید API اوپن\u200cروتر')),
                ('openrouter_model', models.CharField(blank=True, default='openai/gpt-4o', help_text='مثال: openai/gpt-4o, anthropic/claude-3.5-sonnet', max_length=100, verbose_name='مدل AI')),
                ('global_keywords', models.TextField(blank=True, default='', help_text='کلمات کلیدی که روی تمام محصولات اعمال می\u200cشوند', verbose_name='کلمات کلیدی سراسری')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات هوش مصنوعی',
                'verbose_name_plural': 'تنظیمات هوش مصنوعی',
            },
        ),
        migrations.RemoveField(
            model_name='apisettings',
            name='openrouter_api_key',
        ),
        migrations.RemoveField(
            model_name='apisettings',
            name='openrouter_model',
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='target_keywords',
            field=models.TextField(blank=True, default='', help_text='این کلمات کلیدی در تمام محصولات این قالب اعمال می\u200cشوند', verbose_name='کلمات کلیدی هدف (قالب)'),
        ),
    ]
