# Generated by Django 5.2.17 on 2026-09-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0003_aisettings_remove_apisettings_openrouter_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='کلمه کلیدی')),
                ('priority', models.IntegerField(choices=[(1, 'پایین (Low)'), (2, 'متوسط (Medium)'), (3, 'بالا (High)')], default=2, verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کلمه کلیدی سراسری',
                'verbose_name_plural': 'کلمات کلیدی سراسری',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
