# Generated by Django 5.2.17 on 2026-09-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0004_globalkeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisettings',
            name='global_keywords',
        ),
    ]
