# Generated by Django 5.2.17 on 2026-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_app", "0005_remove_aisettings_global_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsync",
            name="source_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='فرمت: [{"id": 12, "name": "موبایل", "slug": "mobile"}]',
                verbose_name="دسته‌بندی‌های منبع",
            ),
        ),
        migrations.AddField(
            model_name="productsync",
            name="target_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="دسته‌بندی‌هایی که محصول با آن‌ها به سایت مقصد ارسال می‌شود",
                verbose_name="دسته‌بندی‌های مقصد",
            ),
        ),
    ]
