# Generated by Django 5.2.17 on 2026-09-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0007_unified_prompt_and_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsync',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='قالبی که برای بازنویسی این محصول به هوش مصنوعی ارسال می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sync_app.prompttemplate', verbose_name='قالب پرامپت'),
        ),
    ]
