# Generated by Django 5.2.17 on 2026-09-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0008_product_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsync',
            name='target_sku',
            field=models.CharField(blank=True, default='', help_text='اگر مبدأ SKU نداشته باشد از روی نام محصول ساخته می\u200cشود.', max_length=120, verbose_name='SKU مقصد'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='prompt',
            field=models.TextField(help_text='یک پرامپت واحد برای توضیح کوتاه و محتوای اصلی. از {product_name}، {seo_keywords} و در محصولات متغیر از {variations} استفاده کنید.', verbose_name='پرامپت'),
        ),
    ]
